version: '3.7'

services:
  thales-frontend-take-home-assignment:
    image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: frontend-take-home-assignment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
