version: 2.1
jobs:
  test_and_lint:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: /home/circleci/frontend-take-home-assignment
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-take-home-assignment-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - frontend-take-home-assignment-deps-develop-{{ checksum "package.json" }}
            - frontend-take-home-assignment-deps-develop
      - run:
          name: Install dependencies
          command: |
            yarn install
      - run:
          name: Linter
          command: |
            yarn run lint
      - run:
          name: Run tests
          command: |
            yarn run test
      - run:
          name: code-coverage
          command: npm run coverage
          - coveralls/upload
          - store_artifacts:
              path: test-results
              prefix: tests
          - store_artifacts:
              path: coverage
              prefix: coverage
          - store_test_results:
              path: test-results
          - run:
              name: "What branch am I on?"
              command: echo ${CIRCLE_BRANCH}
              notify:
                webhooks:
                  - url: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}
      - run:
          name: Run E2E tests
          command: |
            yarn run e2e

workflows:
  version: 2
  pipeline:
    jobs:
      - test_and_lint
